[package]
name = "neo-minecraft-server-launcher"
description = "A low-overhead distributed Minecraft server management tool."
version = "0.1.0"
edition = "2024"
authors = ["Tuxium <ursusfeline07@gmail.com>"]
readme = "README.md"
repository = "https://github.com/LGY07/neo-minecraft-server-launcher"
license = "MIT"

[dependencies]
chrono = "0.4"
toml = "0.9"
serde = { version = "1.0", features = ["derive"] }
colored = "3.0"
reqwest = { version = "0.12", features = ["rustls-tls", "stream"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
hex = "0.4"
indicatif = "0.18"
futures = "0.3"
rustic_core = "0.8"
rustic_backend = "0.5"
zip = "6.0"
tree_magic_mini = "3.2"
lazy_static = "1.5"
regex = "1.12"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1