[package]
name = "PacMine"
description = "A lightweight Minecraft server management tool."
version = "0.1.0"
edition = "2024"
authors = ["Tuxium <ursusfeline07@gmail.com>"]
readme = "README.md"
repository = "https://github.com/LGY07/PacMine"
license = "MIT"

[dependencies]
chrono = "0.4"
toml = "0.9"
serde = { version = "1.0", features = ["derive"] }
colored = "3.0"
reqwest = { version = "0.12", features = ["rustls-tls", "stream"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
hex = "0.4"
indicatif = "0.18"
futures = "0.3"
rustic_core = "0.8"
rustic_backend = "0.5"
zip = "6.0"
lazy_static = "1.5"
regex = "1.12"
infer = "0.19"
simplelog = "0.12"
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
flate2 = "1.1"
tar = "0.4"
sha1 = "0.10"
anyhow = "1.0"
cron_tab = { version = "0.2", features = ["async"] }
axum = { version = "0.8", features = ["http2", "multipart", "ws"] }
serde_json = "1.0"
home = "0.5"
nix = "0.30"
uuid = { version = "1.18", features = ["v4"] }
tokio-stream = "0.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
